/**
 * npm run distances:fetch  — asks the Google Routes API for every route's
 * driving distance and time and writes docs/route-distances.csv for the owner
 * to review (legacy km vs Google km side by side). Keeps the owner's columns
 * (owner_km, owner_time_mins, reviewed, notes) from the previous CSV.
 *
 * npm run distances:apply  — turns the rows marked `reviewed = yes` into
 * src/data/route-distances.generated.ts, which the route builder merges.
 *
 * Nepal routes go through the border crossing Taxiverz uses (route
 * `borderCrossing`, OWNER_TODO D1) as a waypoint; until D1 is answered Google
 * chooses the crossing and the CSV says so.
 *
 * Needs GOOGLE_MAPS_API_KEY in .env.local (Routes API enabled).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { format, resolveConfig } from 'prettier'
import {
  formatMins,
  mergeRows,
  parseCsv,
  parseRoutesResponse,
  routesRequest,
  toCsv,
  verifiedDistances,
  type CsvRow,
} from '../src/lib/distances'

const CSV = 'docs/route-distances.csv'
const GENERATED = 'src/data/route-distances.generated.ts'
const ENDPOINT = 'https://routes.googleapis.com/directions/v2:computeRoutes'

async function apply() {
  if (!existsSync(CSV)) {
    console.error(`${CSV} not found — run npm run distances:fetch first.`)
    process.exit(1)
  }
  const verified = verifiedDistances(parseCsv(readFileSync(CSV, 'utf8')))
  const body = `// Generated by \`npm run distances:apply\` from the owner-reviewed ${CSV}. Do not edit.
import type { VerifiedDistance } from '@/lib/distances'

export const routeDistances: Record<string, VerifiedDistance> = ${JSON.stringify(verified, null, 2)}
`
  // Formatted like the rest of the repo so `format:check` stays green.
  const options = (await resolveConfig(GENERATED)) ?? {}
  writeFileSync(GENERATED, await format(body, { ...options, filepath: GENERATED }))
  console.log(
    `distances:apply — ${Object.keys(verified).length} reviewed route(s) written to ${GENERATED}.`,
  )
}

async function fetchAll() {
  try {
    process.loadEnvFile('.env.local')
  } catch {
    // No .env.local: fall through to the key check.
  }
  const key = process.env.GOOGLE_MAPS_API_KEY?.trim()
  if (!key) {
    console.error(
      'GOOGLE_MAPS_API_KEY is not set (.env.local). Nothing fetched — see OWNER_TODO L3.',
    )
    process.exit(1)
  }
  const { allCities, allRoutes } = await import('../src/lib/content')
  const { getPlaces } = await import('../src/lib/content')
  const places = getPlaces()
  const address = (slug: string) => {
    const c = allCities.find((x) => x.slug === slug)
    if (!c) throw new Error(`Unknown city ${slug}`)
    return { address: `${c.name}, ${c.state}, ${c.country === 'NP' ? 'Nepal' : 'India'}` }
  }

  const rows: CsvRow[] = []
  for (const r of allRoutes) {
    const border = r.borderCrossing ? places.find((p) => p.id === r.borderCrossing) : undefined
    const via = border ? { address: `${border.name}` } : null
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Goog-Api-Key': key,
        'X-Goog-FieldMask': 'routes.distanceMeters,routes.duration',
      },
      body: JSON.stringify(routesRequest(address(r.origin), address(r.destination), via)),
    })
    const result = res.ok ? parseRoutesResponse(await res.json()) : null
    if (!result) console.warn(`  ${r.slug}: no route (${res.status})`)
    const legacyKm = r.legacy.distanceKm
    rows.push({
      slug: r.slug,
      origin: r.origin,
      destination: r.destination,
      legacy_km: legacyKm === null ? '' : String(legacyKm),
      google_km: result ? String(result.km) : '',
      diff_km: result && legacyKm !== null ? String(result.km - legacyKm) : '',
      legacy_time: r.legacy.durationText ?? '',
      google_time: result ? formatMins(result.mins) : '',
      border_used: r.isInternational
        ? border
          ? border.name
          : "Google's choice — confirm the crossing (OWNER_TODO D1)"
        : '',
      owner_km: '',
      owner_time_mins: '',
      reviewed: '',
      notes: '',
    })
    console.log(`  ${r.slug}: ${result ? `${result.km} km, ${formatMins(result.mins)}` : '—'}`)
  }
  const previous = existsSync(CSV) ? parseCsv(readFileSync(CSV, 'utf8')) : []
  writeFileSync(CSV, toCsv(mergeRows(rows, previous)))
  console.log(
    `distances:fetch — ${rows.length} routes written to ${CSV}. The owner reviews it, then run npm run distances:apply.`,
  )
}

if (process.argv.includes('--apply')) await apply()
else await fetchAll()
