/**
 * npm run images:migrate — converts the images listed in scripts/image-manifest.ts
 * from legacy/cleanup-2026-08-03/img to public/images/{key}.webp (≤ 2000px,
 * metadata stripped), then writes src/data/images.generated.ts and docs/IMAGE_MAP.md.
 * Every cleanup image must be either migrated or listed as skipped.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import sharp from 'sharp'
import { manifest, skipped } from './image-manifest'

const SRC = 'legacy/cleanup-2026-08-03/img'
const OUT = 'public/images'
const MAX = 2000

async function main() {
  const files = readdirSync(SRC)
  const used = new Set(manifest.map((m) => m.file))
  const unaccounted = files.filter((f) => !used.has(f) && !(f in skipped))
  const missing = [...used].filter((f) => !files.includes(f))
  const dupKeys = manifest.map((m) => m.key).filter((k, i, a) => a.indexOf(k) !== i)
  if (unaccounted.length || missing.length || dupKeys.length) {
    console.error({ unaccounted, missing, dupKeys })
    process.exit(1)
  }

  const generated: Record<string, unknown> = {}
  const rows: string[] = []
  const legacyNames = invertNameMap()

  for (const entry of manifest) {
    const out = join(OUT, `${entry.key}.webp`)
    mkdirSync(dirname(out), { recursive: true })
    const info = await sharp(join(SRC, entry.file))
      .rotate()
      .resize({ width: MAX, height: MAX, fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 78, effort: 5 })
      .toFile(out)
    generated[entry.key] = {
      src: `/images/${entry.key}.webp`,
      alt: entry.alt,
      width: info.width,
      height: info.height,
      source: entry.source,
      bakedInText: entry.bakedInText ?? false,
      modelMismatch: entry.modelMismatch ?? false,
    }
    const flags = [entry.bakedInText && 'caption baked in', entry.modelMismatch && 'wrong model']
      .filter(Boolean)
      .join(', ')
    rows.push(
      `| \`${legacyNames[entry.file] ?? entry.file}\` | \`${entry.file}\` | \`/images/${entry.key}.webp\` (${info.width}×${info.height}, ${Math.round(info.size / 1024)} KB) | ${entry.source} | ${flags || '—'} | ${entry.note ?? ''} |`,
    )
  }

  const ts = `// Generated by scripts/migrate-images.ts — do not edit by hand. Re-run \`npm run images:migrate\`.
import type { VehicleImage } from '@/lib/schemas/content'

export const images = ${JSON.stringify(generated, null, 2)} as const satisfies Record<string, VehicleImage>

export type ImageKey = keyof typeof images
`
  writeFileSync('src/data/images.generated.ts', ts)

  const placeholderList = readFileSync('legacy/cleanup-2026-08-03/README.md', 'utf8').match(
    /Missing vehicle photos[\s\S]*?(?=\n\n)/,
  )?.[0]
  const md = `# Image map

Generated by \`scripts/migrate-images.ts\` from \`legacy/cleanup-2026-08-03/img\` (the 3 Aug 2026 cleanup: compressed, cleaned filenames). Re-run with \`npm run images:migrate\`.

**Source tags** (from viewing every image, Phase 2): **own** = owner-confirmed photo of a Taxiverz vehicle · **render** = AI/3D render or composited studio image · **stock** = manufacturer or stock photograph/cut-out · **unknown** = a real photo that might be Taxiverz's own — ask the owner.

**No image is \`own\` yet** (OWNER_TODO F1), so under the §5 vehicle gate every vehicle page stays draft. Images with a caption baked in or showing the wrong model are never used as vehicle photos.

## Migrated (${manifest.length})

| Legacy file | Cleanup file | New file | Source | Flags | Note |
|---|---|---|---|---|---|
${rows.join('\n')}

## Not migrated (${Object.keys(skipped).length})

| Cleanup file | Why |
|---|---|
${Object.entries(skipped)
  .map(([f, why]) => `| \`${f}\` | ${why} |`)
  .join('\n')}

## Vehicles with no photo at all

From the cleanup's placeholder list (\`legacy/cleanup-2026-08-03/README.md\`):

> ${(placeholderList ?? 'not found').replace(/\n/g, '\n> ')}

Also without any image: Jaguar F-Type, BMW X3, Ford Endeavour, Hindustan Ambassador, Bentley Continental and Mulsanne, Rolls-Royce Phantom, GMC Yukon Denali, the 3×2, non-AC and sleeper buses, and the 8 off-road bikes.

## Correction to docs/AUDIT.md

The audit repeated the plan's claim that the Gypsy and Jeep **images** are swapped. Viewing them shows the **filenames** are swapped (\`jeep.png\` is a Gypsy, \`gypsy.jpeg\` is an open jeep) but each legacy page displays the right vehicle. The migration names them by what they show.
`
  writeFileSync('docs/IMAGE_MAP.md', md)
  console.log(
    `images:migrate OK — ${manifest.length} migrated, ${Object.keys(skipped).length} skipped.`,
  )
}

function invertNameMap(): Record<string, string> {
  const { map } = JSON.parse(readFileSync('legacy/cleanup-2026-08-03/name-map.json', 'utf8')) as {
    map: Record<string, string>
  }
  return Object.fromEntries(Object.entries(map).map(([legacy, clean]) => [clean, legacy]))
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
