// Generated by `npm run distances:apply` from the owner-reviewed docs/route-distances.csv. Do not edit.
import type { VerifiedDistance } from '@/lib/distances'

export const routeDistances: Record<string, VerifiedDistance> = {}
